//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PundolsTestOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Credits { get; set; }
        public string EnrolmentDate { get; set; }
        public byte[] VersionNo { get; set; }
    }
}
